# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 20:37
from __future__ import unicode_literals

import ddnet.validators
from django.db import migrations, models
import django.db.models.deletion
import maps.fields
import maps.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('name', models.CharField(db_column='Map', max_length=128, primary_key=True, serialize=False)),
                ('mapper', models.CharField(blank=True, db_column='Mapper', max_length=128)),
                ('points', models.IntegerField(db_column='Points', default=0)),
                ('stars', models.IntegerField(choices=[(0, '☆☆☆☆☆'), (1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], db_column='Stars', default=0)),
                ('timestamp', models.DateTimeField(blank=True, db_column='Timestamp')),
            ],
            options={
                'db_table': 'record_maps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MapCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('order', models.IntegerField()),
            ],
        ),
#        migrations.CreateModel(
#            name='MapFix',
#            fields=[
#                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                ('mapfile', maps.fields.MapFileField(upload_to='mapfixes')),
#                ('fix_state', models.IntegerField(choices=[(0, 'NOT_STARTED'), (1, 'PENDING'), (2, 'DONE'), (3, 'FAILED')], default=0)),
#                ('log', models.TextField(blank=True, default='', editable=False)),
#                ('ddmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.Map')),
#            ],
#        ),
        migrations.CreateModel(
            name='MapRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, validators=[maps.models.validate_mapname])),
                ('mapfile', maps.fields.MapFileField(upload_to='mapreleases')),
                ('mapper', models.CharField(blank=True, max_length=128)),
                ('img', maps.fields.MapImageField(upload_to='mapreleases', validators=[ddnet.validators.image_validator(1440, 900)])),
                ('stars', models.IntegerField(choices=[(0, '☆☆☆☆☆'), (1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], default=0)),
                ('release_date', models.DateTimeField()),
                ('release_state', models.IntegerField(choices=[(0, 'NOT_STARTED'), (1, 'PENDING'), (2, 'DONE'), (3, 'FAILED')], default=0)),
                ('log', models.TextField(blank=True, default='', editable=False)),
                ('categories', models.ManyToManyField(blank=True, to='maps.MapCategory')),
            ],
            options={
                'permissions': (('can_release_map', 'Can release maps'),),
            },
        ),
        migrations.CreateModel(
            name='ServerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('offset', models.IntegerField()),
                ('multiplier', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='maprelease',
            name='server_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maps.ServerType'),
        ),
    ]
