# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapFix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapfile', maps.fields.MapFileField(upload_to='mapfixes')),
                ('fix_state', models.IntegerField(choices=[(0, 'NOT_STARTED'), (1, 'PENDING'), (2, 'DONE'), (3, 'FAILED')], default=0)),
                ('log', models.TextField(blank=True, default='', editable=False)),
                ('ddmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.Map')),
            ],
        ),
    ]
