# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_mapfix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maprelease',
            name='log',
        ),
    ]
