# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_remove_maprelease_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='maprelease',
            name='log',
            field=models.TextField(blank=True, default='', editable=False),
        ),
    ]
