# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_maprelease_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('state', models.IntegerField(choices=[(0, 'NOT_STARTED'), (1, 'PENDING'), (2, 'DONE'), (3, 'FAILED')], default=0)),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
        migrations.CreateModel(
            name='ReleaseLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('state', models.IntegerField(choices=[(0, 'NOT_STARTED'), (1, 'PENDING'), (2, 'DONE'), (3, 'FAILED')], default=0)),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
        migrations.AlterModelOptions(
            name='map',
            options={'managed': False, 'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='mapcategory',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='mapfix',
            options={'ordering': ('mapfile',)},
        ),
        migrations.AlterModelOptions(
            name='maprelease',
            options={'ordering': ('name',), 'permissions': (('can_release_map', 'Can release maps'),)},
        ),
        migrations.AlterModelOptions(
            name='servertype',
            options={'ordering': ('name',)},
        ),
        migrations.RenameField(
            model_name='mapfix',
            old_name='fix_state',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='maprelease',
            old_name='release_state',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='mapfix',
            name='log',
        ),
        migrations.RemoveField(
            model_name='maprelease',
            name='log',
        ),
        migrations.AddField(
            model_name='mapfix',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=None),
            preserve_default=False,
        ),
    ]
