# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 23:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0006_auto_20170330_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledMapRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateTimeField()),
                ('broadcast', models.CharField(blank=True, max_length=128)),
                ('state', models.IntegerField(choices=[(0, 'NOT_STARTED'), (1, 'PENDING'), (2, 'DONE'), (3, 'FAILED')], default=0)),
            ],
            options={
                'ordering': ('release_date',),
            },
        ),
        migrations.AlterModelOptions(
            name='fixlog',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.AlterModelOptions(
            name='releaselog',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.RemoveField(
            model_name='maprelease',
            name='release_date',
        ),
        migrations.AddField(
            model_name='maprelease',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mapfix',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='scheduledmaprelease',
            name='maps',
            field=models.ManyToManyField(to='maps.MapRelease'),
        ),
    ]
