# Generated by Django 3.2.19 on 2023-07-06 15:01

from django.db import migrations
import maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0007_auto_20170401_0159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapfix',
            options={'ordering': ('mapfile',), 'permissions': (('can_fix_map', 'Can fix maps'),)},
        ),
        migrations.AlterField(
            model_name='maprelease',
            name='img',
            field=maps.fields.MapImageField(upload_to='mapreleases'),
        ),
    ]
