# Generated by Django 3.2.19 on 2023-07-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('can_broadcast', 'Can the user do broadcasts on DDNet Servers'),),
                'managed': False,
            },
        ),
    ]
