# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 16:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=23, unique=True)),
                ('creator', models.CharField(max_length=15)),
                ('pack', models.CharField(max_length=64)),
                ('release_date', models.DateTimeField(default=datetime.datetime.now)),
                ('skin_image', models.ImageField(upload_to='skins')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
