# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 01:28
from __future__ import unicode_literals

import ddnet.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skin',
            name='skin_image',
            field=models.ImageField(upload_to='skins', validators=[ddnet.validators.image_validator(256, 128)]),
        ),
    ]
