[uwsgi]
plugins=python3
chdir=/home/django/ddnet-django
virtualenv=/home/django/ddnet-django/.venv
env=DJANGO_SETTINGS_MODULE=ddnet_django.settings_private
master=true
max-requests=5000
socket=/tmp/django.sock
chmod-socket=660
vacuum=true
die-on-term=true
enable-threads=true
buffer-size=32768
manage-script-name=true
mount=/django=ddnet_django.wsgi:application
